[package]
name = "arise"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.81"
clap = { version = "4.5.4", features = ["derive"] }
derive_more = "0.99.17"
hyprland = "0.3.13"


# [[bin]]
# name
