# TODO(pr): submit this example as a pr to https://github.com/nix-community/nixd
[language-server.nixd]
command = "nixd"
args = ["--inlay-hints", "--semantic-tokens"]

[language-server.nixd.config.nixd.options]
# nixos = { expr = '(builtins.getFlake "/home/kpbaks/dotfiles").nixosConfigurations.nixos.options' }
# home-manager = { expr = '(builtins.getFlake "/home/kpbaks/dotfiles").homeConfigurations."kpbaks@nixos".options' }
nixos = { expr = '(builtins.getFlake "/etc/nixos").nixosConfigurations.nixos.options' }
home-manager = { expr = '(builtins.getFlake "/etc/nixos").homeConfigurations."kpbaks@nixos".options' }


# https://github.com/oxalica/nil/blob/main/docs/configuration.md
[language-server.nil.config.nil]
nix = { flake = { autoArchive = true } }


[[language]]
name = "nix"
language-servers = ["nixd", "nil", "typos-lsp"]

# [[language]]
# name = "git-commit"
# scope = "git.commitmsg"
# file-types = [
#   { glob = "COMMIT_EDITMSG" },
#   { glob = "MERGE_MSG" },
#   { glob = "NOTES_EDITMSG" },
# ]
# comment-token = "#"
# indent = { tab-width = 2, unit = "  " }
# rulers = [51, 73]
# text-width = 72
